stages:
  ocr_stage:
    cmd: python kyc_onboarding_assistant/scripts/run_ocr.py
    deps:
    - kyc_onboarding_assistant/scripts/run_ocr.py
    outs:
    - kyc_onboarding_assistant/output/ocr_output.txt
  llm_stage:
    cmd: python kyc_onboarding_assistant/scripts/run_llm.py
    deps:
    - kyc_onboarding_assistant/output/ocr_output.txt
    - kyc_onboarding_assistant/scripts/run_llm.py
    outs:
    - kyc_onboarding_assistant/output/llm_output.json
  validation_stage:
    cmd: python kyc_onboarding_assistant/scripts/run_validation.py
    deps:
    - kyc_onboarding_assistant/output/llm_output.json
    - kyc_onboarding_assistant/scripts/run_validation.py
    outs:
    - kyc_onboarding_assistant/output/validation_output.json
